// Run against a separate local replay generated by tools/ground_demo.py.
// This test changes that replay's controls, never a camera or flight device.
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs');

(async () => {
  const url = new URL(process.env.GROUND_URL || 'http://127.0.0.1:8773/');
  assert.ok(['127.0.0.1', 'localhost'].includes(url.hostname), 'Use an isolated local replay');
  const browser = await chromium.launch({channel: 'chrome', headless: true, args: ['--enable-gpu']});
  const failures = [];
  const snapshot = page => page.evaluate(() => window.pigeonGround.snapshot());
  const pageFor = async route => {
    const page = await browser.newPage({viewport: {width: 1600, height: 900}});
    page.on('pageerror', e => failures.push(e.message));
    await page.goto(new URL(route, url).href);
    await page.waitForFunction(() => window.pigeonGround?.snapshot().connected);
    return page;
  };
  const near = (a, b) => assert.ok(Math.abs(a - b) < .001, `${a} != ${b}`);
  const heading = page => page.evaluate(() => window.pigeonGround.snapshot().navigation.yaw);
  try {
    const operator = await pageFor('/');
    await operator.click('#controls-toggle');
    await operator.locator('#operator-controls').waitFor({state: 'visible'});
    if (await operator.locator('#take-control').isVisible()) await operator.click('#take-control');
    await operator.waitForFunction(() => window.pigeonGround.snapshot().station.controlling);
    await operator.selectOption('#view', 'perspective');
    assert.equal(await operator.locator('#advanced-controls').getAttribute('open'), null);
    assert.equal(await operator.locator('#view-presets button').count(), 6);
    assert.equal(await operator.locator('#extra-presets button').count(), 3);
    await operator.locator('#advanced-controls > summary').click();
    await operator.click('#home');
    await operator.getByRole('button', {name: 'Restart', exact: true}).click();
    await operator.getByRole('button', {name: 'Play', exact: true}).click();
    await operator.waitForFunction(() => window.pigeonGround.snapshot().station.mission.pressureFresh);
    await operator.getByRole('button', {name: 'Pause', exact: true}).click();
    await operator.click('#pad-reference');
    await operator.waitForFunction(() => window.pigeonGround.snapshot().station.mission.reference !== null);
    const paused = await snapshot(operator);
    assert.ok(paused.calibrated);
    assert.equal(paused.station.mission.simulated, true);
    assert.ok(Math.abs(paused.station.mission.altitude) < 1);
    const audience = await pageFor('/?mode=audience');
    await audience.waitForFunction(pts => window.pigeonGround.snapshot().pair?.a >= pts, paused.pair.a);
    assert.equal((await snapshot(operator)).pair.a, paused.pair.a, 'A late audience must not rewind replay');
    assert.equal((await snapshot(audience)).station.controlling, false);
    await audience.waitForFunction(() => window.pigeonGround.snapshot().station.mission.reference !== null);
    near((await snapshot(audience)).station.mission.altitude, paused.station.mission.altitude);
    assert.equal(await audience.locator('#controls-toggle').isVisible(), false);

    await operator.click('#controls-toggle');
    await operator.focus('#image');
    const startYaw = await heading(operator);
    await operator.keyboard.down('ArrowRight');
    await operator.waitForTimeout(400);
    await operator.keyboard.up('ArrowRight');
    await operator.waitForTimeout(600);
    const moved = await heading(operator);
    assert.ok(moved - startYaw > .15, 'Keyboard moves view');
    await audience.waitForFunction(yaw => Math.abs(window.pigeonGround.snapshot().navigation.yaw - yaw) < .001, moved);
    await operator.keyboard.down('KeyE');
    await operator.waitForTimeout(400);
    await operator.keyboard.up('KeyE');
    await operator.waitForTimeout(600);
    const rolled = (await snapshot(operator)).navigation.roll;
    assert.ok(rolled > .15, 'E tilts the view');
    near(await heading(operator), moved);
    await audience.waitForFunction(roll => Math.abs(window.pigeonGround.snapshot().navigation.roll - roll) < .001, rolled);
    await operator.keyboard.press('Shift+7');
    await operator.keyboard.press('2');
    await operator.waitForTimeout(700);
    assert.ok(Math.abs(await heading(operator)) > 3);
    near((await snapshot(operator)).navigation.roll, 0);
    await operator.keyboard.press('7');
    await operator.waitForTimeout(700);
    near(await heading(operator), moved);
    near((await snapshot(operator)).navigation.roll, rolled);
    assert.equal(await operator.evaluate(() => JSON.parse(localStorage.getItem('pigeonvision.viewPresets.v1'))[6].name), 'Saved 7');

    // A held navigation key cannot keep moving after focus leaves the page.
    await operator.keyboard.down('KeyD');
    await operator.waitForTimeout(100);
    await operator.evaluate(() => window.dispatchEvent(new Event('blur')));
    const onBlur = await heading(operator);
    await operator.keyboard.up('KeyD');
    await operator.waitForTimeout(150);
    near(await heading(operator), onBlur);
    near((await snapshot(operator)).navigation.roll, rolled);
    await operator.click('#controls-toggle');
    await operator.locator('summary').filter({hasText: 'Projection & pairing'}).click();
    await operator.focus('#max-skew');
    await operator.keyboard.press('ArrowLeft');
    near(await heading(operator), onBlur);
    await operator.fill('#max-skew', '30');
    await operator.locator('#max-skew').dispatchEvent('change');
    await audience.waitForFunction(() => window.pigeonGround.snapshot().pairingGapMs === 30);
    await audience.locator('#max-skew').evaluate(input => {input.value = '200'; input.dispatchEvent(new Event('change'));});
    assert.equal((await snapshot(audience)).pairingGapMs, 30);
    assert.equal(await audience.inputValue('#max-skew'), '30');
    await operator.selectOption('#view', 'b');
    await operator.locator('#focus-zoom').fill('3');
    await operator.locator('#focus-zoom').dispatchEvent('input');
    const expectedRotation = (await snapshot(operator)).viewerRotation.B === 180 ? 0 : 180;
    await operator.click('#rotate-view');
    await audience.waitForFunction(rotation => {
      const s = window.pigeonGround.snapshot();
      return s.navigation.mode === 'b' && s.focus.B.zoom === 3 && s.viewerRotation.B === rotation;
    }, expectedRotation);
    await operator.selectOption('#seam', '3');
    await operator.selectOption('#view', 'perspective');
    await operator.getByRole('button', {name: 'Restart', exact: true}).click();
    await operator.waitForFunction(pts => window.pigeonGround.snapshot().pair?.a < pts, paused.pair.a);
    assert.equal((await snapshot(operator)).navigation.mode, 'perspective');
    near(await heading(operator), onBlur);

    // Reconnecting owner accepts cached pose, but its own echoes cannot cancel animation.
    await operator.reload();
    await operator.waitForFunction(() => window.pigeonGround?.snapshot().station.controlling);
    await operator.waitForFunction(yaw => Math.abs(window.pigeonGround.snapshot().navigation.yaw - yaw) < .001, onBlur);
    assert.equal((await snapshot(operator)).viewerRotation.B, expectedRotation);
    near((await snapshot(operator)).navigation.roll, rolled);
    const savedAgain = await operator.evaluate(() => JSON.parse(localStorage.getItem('pigeonvision.viewPresets.v1'))[6]);
    near(savedAgain.yaw, moved);

    const other = await pageFor('/');
    assert.equal(await other.locator('#take-control').isVisible(), true, 'Control handoff is visible without opening the menu');
    assert.equal(await other.locator('#controls-toggle').getAttribute('aria-expanded'), 'false');
    await other.click('#take-control');
    await operator.waitForFunction(() => !window.pigeonGround.snapshot().station.controlling);
    await other.waitForFunction(() => window.pigeonGround.snapshot().station.controlling);
    await other.focus('#image');
    const imageBox = await other.locator('#image').boundingBox();
    const beforeDrag = await heading(other);
    await other.mouse.move(imageBox.width / 2, imageBox.height / 2);
    await other.mouse.down();
    await other.mouse.move(imageBox.width / 2 + 60, imageBox.height / 2, {steps: 4});
    await other.mouse.up();
    assert.ok(Math.abs(await heading(other) - beforeDrag) > .1, 'Mouse panning works after taking control in another tab');
    await other.keyboard.press('3');
    await other.waitForTimeout(750);
    await operator.waitForFunction(() => Math.abs(window.pigeonGround.snapshot().navigation.yaw - Math.PI / 2) < .001);
    await audience.focus('#image');
    await audience.keyboard.press('1');
    near(await heading(audience), Math.PI / 2);

    await other.focus('#image');
    await other.keyboard.press('1');
    await other.click('#controls-toggle');
    await other.getByRole('button', {name: 'Restart', exact: true}).click();
    await other.waitForFunction(() => window.pigeonGround.snapshot().pair?.a === 0);
    await other.click('#pad-reference');
    await other.getByRole('button', {name: 'Play', exact: true}).click();
    await other.waitForFunction(() => window.pigeonGround.snapshot().pair?.a >= 12000000);
    await other.getByRole('button', {name: 'Pause', exact: true}).click();
    await other.waitForFunction(() => window.pigeonGround.snapshot().station.mission.elapsed >= 9);
    const ascent = (await snapshot(other)).station.mission;
    assert.equal(ascent.phase, 'ASCENT');
    assert.ok(ascent.altitude > 1000 && ascent.speed > 0);
    const late = await pageFor('/?mode=audience');
    await late.waitForFunction(() => window.pigeonGround.snapshot().station.mission.elapsed >= 9);
    const lateAscent = (await snapshot(late)).station.mission;
    assert.equal(lateAscent.events[0].event, 'LAUNCH', 'Mission events survive the recent telemetry cache');
    assert.ok(Math.abs(lateAscent.elapsed - ascent.elapsed) < .1);

    const out = process.env.GROUND_SCREENSHOT;
    if (out) {
      fs.mkdirSync(path.dirname(out), {recursive: true});
      await late.waitForFunction(() => document.getElementById('hud-altitude-plot').getAttribute('d'));
      await late.evaluate(() => document.fonts.ready);
      assert.equal(await late.evaluate(() => document.fonts.check('300 100px "Plex Condensed"')), true);
      await late.screenshot({path: out});
    }
    assert.deepEqual(failures, []);
    console.log(JSON.stringify({passed: true, checked: ['real H264 replay', 'late audience GOP', 'pad reference relay',
      'keyboard pan and release', 'preset save/recall/persistence', 'blur stops motion', 'editing ignores navigation',
      'Q/E roll and audience relay', 'roll presets and reconnect', 'visible control handoff and mouse drag',
      'raw zoom/rotation relay', 'restart preserves view', 'owner reconnect restores view', 'ownership transfer', 'readonly audience',
      'ascent telemetry aligned to decoded video', 'late audience retains launch event']}));
  } finally { await browser.close(); }
})().catch(error => {console.error(error); process.exitCode = 1;});
